### ISSUE TITLE
Create an empty article [3]

### ISSUE THREAD

**Issue by nevtay** [snaphunters/snapi#12]
## User Story

**AS A**
Content Creator

**I WANT TO**
create a new article

**SO THAT**
I can share information about a particular topic

## Acceptance Criteria 1

**GIVEN**
I want to create a new article 

**WHEN**
I click on a button or link to add a new article from the Dashboard

**THEN**
I should be taken to the article editor page 

## Acceptance Criteria 2

**GIVEN**
I am in the Editor

**WHEN**
the page loads

**THEN**
the title and the main article container are loaded

## Acceptance Criteria 3

**GIVEN**
I am in the Editor

**WHEN**
I click on the title input field

**THEN**
I can type in a title

**Comment by enwee** [comment]
Requirements have been superseded and captured in #32
