### ISSUE TITLE
Add an image block type [2]

### ISSUE THREAD

**Issue by vallq** [snaphunters/snapi#14]
## User Story

**AS A**
Content Creator
**I WANT TO**
Add an image block
**SO THAT**
my Article can have pictures included

## Acceptance Criteria

**GIVEN**
I have created an Article
**WHEN**
I click on the ADD BLOCK
**THEN**
I can select an image-type block, which allows me to add an image from a source (e.g. url) to my Article

**Comment by nevtay** [comment]
Question for PO
- Are images hosted on an internal or external server?
  - If we store it on an internal server, there could be potential issues (e.g. loading times, quality) caused by file-size limitations set by the server

**Comment by Jonwyp** [comment]
Closed and merged with #16
