### ISSUE TITLE
Add a sub-topic to an article [3]

### ISSUE THREAD

**Issue by nicchunglow** [snaphunters/snapi#9]
## User Story

**AS A** Content Creator
**I WANT TO** be able to add sub-topic to my articles
**SO THAT** my articles are searchable by sub-topic. 

## Acceptance Criteria

**GIVEN** that I have already in add article mode after clicking the add article button, 
**WHEN** I want to add a sub-topic
**THEN** I am able to input the sub-topic and wait to be saved.

**Comment by Jonwyp** [comment]
Closed. Duplicate of #31
